/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created: Thu Jan 12 14:31:21 2012
**      by: Qt User Interface Compiler version 4.8.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QDial>
#include <QtGui/QDoubleSpinBox>
#include <QtGui/QFrame>
#include <QtGui/QGraphicsView>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QMainWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QProgressBar>
#include <QtGui/QPushButton>
#include <QtGui/QRadioButton>
#include <QtGui/QTabWidget>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *connectAction;
    QWidget *centralWidget;
    QLineEdit *Connect2;
    QLabel *AccLabel_2;
    QTabWidget *tabWidget;
    QWidget *attitudeControlTab;
    QGroupBox *currentQuaternionBox;
    QLabel *cur_q0_label;
    QLabel *cur_q1_label;
    QLabel *cur_q2_label;
    QLabel *cur_q3_label;
    QDoubleSpinBox *cur_q0_spinbox;
    QDoubleSpinBox *cur_q1_spinbox;
    QDoubleSpinBox *cur_q2_spinbox;
    QDoubleSpinBox *cur_q3_spinbox;
    QGroupBox *setupQuaternionBox;
    QDial *roll_dial;
    QDial *pitch_dial;
    QDial *yaw_dial;
    QLabel *roll_label;
    QLabel *yaw_label;
    QLabel *pitch_label;
    QLabel *q0_label;
    QLabel *q1_label;
    QLabel *q2_label;
    QLabel *q3_label;
    QFrame *horizontalSeparation;
    QDoubleSpinBox *roll_spinbox;
    QDoubleSpinBox *pitch_spinbox;
    QDoubleSpinBox *yaw_spinbox;
    QDoubleSpinBox *q3_spinbox;
    QDoubleSpinBox *q2_spinbox;
    QDoubleSpinBox *q1_spinbox;
    QDoubleSpinBox *q0_spinbox;
    QRadioButton *coarseAlignment_radiobutton;
    QRadioButton *fineAlignment_radiobutton;
    QFrame *line;
    QPushButton *simulationButton;
    QWidget *sensorReadingsTab;
    QGroupBox *accelerometerBox;
    QLabel *accelX_label;
    QLabel *accelY_label;
    QLabel *accelZ_label;
    QDoubleSpinBox *accelX_spinbox;
    QDoubleSpinBox *accelY_spinbox;
    QDoubleSpinBox *accelZ_spinbox;
    QProgressBar *progressBarAccXPos;
    QProgressBar *progressBarAccXNeg;
    QProgressBar *progressBarAccYNeg;
    QProgressBar *progressBarAccYPos;
    QProgressBar *progressBarAccZPos;
    QProgressBar *progressBarAccZNeg;
    QGroupBox *gyroscopeBox;
    QLabel *gyroX_label;
    QLabel *gyroY_label;
    QLabel *gyroZ_label;
    QDoubleSpinBox *gyroX_spinbox;
    QDoubleSpinBox *gyroY_spinbox;
    QDoubleSpinBox *gyroZ_spinbox;
    QProgressBar *progressBarGyroXNeg;
    QProgressBar *progressBarGyroYNeg;
    QProgressBar *progressBarGyroZNeg;
    QProgressBar *progressBarGyroXPos;
    QProgressBar *progressBarGyroYPos;
    QProgressBar *progressBarGyroZPos;
    QGroupBox *magnetoBox;
    QLabel *magX_label;
    QLabel *magY_label;
    QLabel *magZ_label;
    QDoubleSpinBox *magX_spinbox;
    QDoubleSpinBox *magY_spinbox;
    QDoubleSpinBox *magZ_spinbox;
    QProgressBar *progressBarMagXNeg;
    QProgressBar *progressBarMagYNeg;
    QProgressBar *progressBarMagZNeg;
    QProgressBar *progressBarMagXPos;
    QProgressBar *progressBarMagYPos;
    QProgressBar *progressBarMagZPos;
    QGroupBox *groupBox;
    QProgressBar *progressBar1Neg;
    QProgressBar *progressBar2Neg;
    QProgressBar *progressBar3Neg;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QProgressBar *progressBar1Pos;
    QProgressBar *progressBar2Pos;
    QProgressBar *progressBar3Pos;
    QGraphicsView *IR_graphics;
    QLabel *IR_label;
    QLabel *state_label;
    QLabel *state_label2;
    QMenuBar *menuBar;
    QMenu *menuConnection;
    QMenu *menuAbout;
    QMenu *menuWindow;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(800, 539);
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/graphic/logoSC.ico"), QSize(), QIcon::Normal, QIcon::Off);
        MainWindow->setWindowIcon(icon);
        MainWindow->setToolButtonStyle(Qt::ToolButtonFollowStyle);
        connectAction = new QAction(MainWindow);
        connectAction->setObjectName(QString::fromUtf8("connectAction"));
        connectAction->setShortcutContext(Qt::WidgetShortcut);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        Connect2 = new QLineEdit(centralWidget);
        Connect2->setObjectName(QString::fromUtf8("Connect2"));
        Connect2->setGeometry(QRect(560, 10, 221, 20));
        AccLabel_2 = new QLabel(centralWidget);
        AccLabel_2->setObjectName(QString::fromUtf8("AccLabel_2"));
        AccLabel_2->setGeometry(QRect(440, 10, 121, 20));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(20, 50, 761, 441));
        attitudeControlTab = new QWidget();
        attitudeControlTab->setObjectName(QString::fromUtf8("attitudeControlTab"));
        currentQuaternionBox = new QGroupBox(attitudeControlTab);
        currentQuaternionBox->setObjectName(QString::fromUtf8("currentQuaternionBox"));
        currentQuaternionBox->setGeometry(QRect(290, 250, 431, 141));
        cur_q0_label = new QLabel(currentQuaternionBox);
        cur_q0_label->setObjectName(QString::fromUtf8("cur_q0_label"));
        cur_q0_label->setGeometry(QRect(30, 30, 71, 16));
        cur_q0_label->setAlignment(Qt::AlignCenter);
        cur_q1_label = new QLabel(currentQuaternionBox);
        cur_q1_label->setObjectName(QString::fromUtf8("cur_q1_label"));
        cur_q1_label->setGeometry(QRect(130, 30, 71, 16));
        cur_q1_label->setAlignment(Qt::AlignCenter);
        cur_q2_label = new QLabel(currentQuaternionBox);
        cur_q2_label->setObjectName(QString::fromUtf8("cur_q2_label"));
        cur_q2_label->setGeometry(QRect(230, 30, 71, 16));
        cur_q2_label->setAlignment(Qt::AlignCenter);
        cur_q3_label = new QLabel(currentQuaternionBox);
        cur_q3_label->setObjectName(QString::fromUtf8("cur_q3_label"));
        cur_q3_label->setGeometry(QRect(330, 30, 71, 16));
        cur_q3_label->setAlignment(Qt::AlignCenter);
        cur_q0_spinbox = new QDoubleSpinBox(currentQuaternionBox);
        cur_q0_spinbox->setObjectName(QString::fromUtf8("cur_q0_spinbox"));
        cur_q0_spinbox->setGeometry(QRect(30, 50, 71, 25));
        cur_q0_spinbox->setReadOnly(true);
        cur_q1_spinbox = new QDoubleSpinBox(currentQuaternionBox);
        cur_q1_spinbox->setObjectName(QString::fromUtf8("cur_q1_spinbox"));
        cur_q1_spinbox->setGeometry(QRect(130, 50, 71, 25));
        cur_q1_spinbox->setReadOnly(true);
        cur_q2_spinbox = new QDoubleSpinBox(currentQuaternionBox);
        cur_q2_spinbox->setObjectName(QString::fromUtf8("cur_q2_spinbox"));
        cur_q2_spinbox->setGeometry(QRect(230, 50, 71, 25));
        cur_q2_spinbox->setReadOnly(true);
        cur_q3_spinbox = new QDoubleSpinBox(currentQuaternionBox);
        cur_q3_spinbox->setObjectName(QString::fromUtf8("cur_q3_spinbox"));
        cur_q3_spinbox->setGeometry(QRect(330, 50, 71, 25));
        cur_q3_spinbox->setReadOnly(true);
        setupQuaternionBox = new QGroupBox(attitudeControlTab);
        setupQuaternionBox->setObjectName(QString::fromUtf8("setupQuaternionBox"));
        setupQuaternionBox->setGeometry(QRect(290, 10, 431, 231));
        roll_dial = new QDial(setupQuaternionBox);
        roll_dial->setObjectName(QString::fromUtf8("roll_dial"));
        roll_dial->setGeometry(QRect(40, 30, 71, 91));
        roll_dial->setMinimum(-4500);
        roll_dial->setMaximum(4500);
        roll_dial->setPageStep(10);
        roll_dial->setValue(0);
        roll_dial->setOrientation(Qt::Horizontal);
        pitch_dial = new QDial(setupQuaternionBox);
        pitch_dial->setObjectName(QString::fromUtf8("pitch_dial"));
        pitch_dial->setGeometry(QRect(180, 30, 71, 91));
        pitch_dial->setAutoFillBackground(false);
        pitch_dial->setMinimum(-4500);
        pitch_dial->setMaximum(4500);
        pitch_dial->setSingleStep(1);
        pitch_dial->setPageStep(10);
        pitch_dial->setInvertedAppearance(false);
        pitch_dial->setInvertedControls(false);
        pitch_dial->setWrapping(false);
        pitch_dial->setNotchTarget(3.7);
        pitch_dial->setNotchesVisible(false);
        yaw_dial = new QDial(setupQuaternionBox);
        yaw_dial->setObjectName(QString::fromUtf8("yaw_dial"));
        yaw_dial->setGeometry(QRect(320, 30, 71, 91));
        yaw_dial->setMinimum(-18000);
        yaw_dial->setMaximum(18000);
        yaw_dial->setWrapping(true);
        yaw_dial->setNotchesVisible(false);
        roll_label = new QLabel(setupQuaternionBox);
        roll_label->setObjectName(QString::fromUtf8("roll_label"));
        roll_label->setGeometry(QRect(50, 30, 51, 16));
        roll_label->setAlignment(Qt::AlignCenter);
        yaw_label = new QLabel(setupQuaternionBox);
        yaw_label->setObjectName(QString::fromUtf8("yaw_label"));
        yaw_label->setGeometry(QRect(330, 30, 51, 16));
        yaw_label->setAlignment(Qt::AlignCenter);
        pitch_label = new QLabel(setupQuaternionBox);
        pitch_label->setObjectName(QString::fromUtf8("pitch_label"));
        pitch_label->setGeometry(QRect(190, 30, 51, 16));
        pitch_label->setAlignment(Qt::AlignCenter);
        q0_label = new QLabel(setupQuaternionBox);
        q0_label->setObjectName(QString::fromUtf8("q0_label"));
        q0_label->setGeometry(QRect(30, 170, 71, 16));
        q0_label->setAlignment(Qt::AlignCenter);
        q1_label = new QLabel(setupQuaternionBox);
        q1_label->setObjectName(QString::fromUtf8("q1_label"));
        q1_label->setGeometry(QRect(130, 170, 71, 16));
        q1_label->setAlignment(Qt::AlignCenter);
        q2_label = new QLabel(setupQuaternionBox);
        q2_label->setObjectName(QString::fromUtf8("q2_label"));
        q2_label->setGeometry(QRect(230, 170, 71, 16));
        q2_label->setAlignment(Qt::AlignCenter);
        q3_label = new QLabel(setupQuaternionBox);
        q3_label->setObjectName(QString::fromUtf8("q3_label"));
        q3_label->setGeometry(QRect(330, 170, 71, 16));
        q3_label->setAlignment(Qt::AlignCenter);
        horizontalSeparation = new QFrame(setupQuaternionBox);
        horizontalSeparation->setObjectName(QString::fromUtf8("horizontalSeparation"));
        horizontalSeparation->setGeometry(QRect(27, 150, 381, 20));
        horizontalSeparation->setFrameShape(QFrame::HLine);
        horizontalSeparation->setFrameShadow(QFrame::Sunken);
        roll_spinbox = new QDoubleSpinBox(setupQuaternionBox);
        roll_spinbox->setObjectName(QString::fromUtf8("roll_spinbox"));
        roll_spinbox->setGeometry(QRect(30, 120, 91, 25));
        roll_spinbox->setMinimum(-45);
        roll_spinbox->setMaximum(45);
        roll_spinbox->setValue(0);
        pitch_spinbox = new QDoubleSpinBox(setupQuaternionBox);
        pitch_spinbox->setObjectName(QString::fromUtf8("pitch_spinbox"));
        pitch_spinbox->setGeometry(QRect(170, 120, 91, 25));
        pitch_spinbox->setDecimals(2);
        pitch_spinbox->setMinimum(-45);
        pitch_spinbox->setMaximum(45);
        yaw_spinbox = new QDoubleSpinBox(setupQuaternionBox);
        yaw_spinbox->setObjectName(QString::fromUtf8("yaw_spinbox"));
        yaw_spinbox->setGeometry(QRect(310, 120, 91, 25));
        yaw_spinbox->setMinimum(-180);
        yaw_spinbox->setMaximum(180);
        q3_spinbox = new QDoubleSpinBox(setupQuaternionBox);
        q3_spinbox->setObjectName(QString::fromUtf8("q3_spinbox"));
        q3_spinbox->setGeometry(QRect(330, 190, 71, 25));
        q3_spinbox->setReadOnly(true);
        q3_spinbox->setDecimals(3);
        q3_spinbox->setMinimum(-1);
        q3_spinbox->setMaximum(1);
        q2_spinbox = new QDoubleSpinBox(setupQuaternionBox);
        q2_spinbox->setObjectName(QString::fromUtf8("q2_spinbox"));
        q2_spinbox->setGeometry(QRect(230, 190, 71, 25));
        q2_spinbox->setReadOnly(true);
        q2_spinbox->setDecimals(3);
        q2_spinbox->setMinimum(-1);
        q2_spinbox->setMaximum(1);
        q1_spinbox = new QDoubleSpinBox(setupQuaternionBox);
        q1_spinbox->setObjectName(QString::fromUtf8("q1_spinbox"));
        q1_spinbox->setGeometry(QRect(130, 190, 71, 25));
        q1_spinbox->setReadOnly(true);
        q1_spinbox->setDecimals(3);
        q1_spinbox->setMinimum(-1);
        q1_spinbox->setMaximum(1);
        q0_spinbox = new QDoubleSpinBox(setupQuaternionBox);
        q0_spinbox->setObjectName(QString::fromUtf8("q0_spinbox"));
        q0_spinbox->setGeometry(QRect(30, 190, 71, 25));
        q0_spinbox->setReadOnly(true);
        q0_spinbox->setDecimals(3);
        q0_spinbox->setMinimum(-1);
        q0_spinbox->setMaximum(1);
        coarseAlignment_radiobutton = new QRadioButton(attitudeControlTab);
        coarseAlignment_radiobutton->setObjectName(QString::fromUtf8("coarseAlignment_radiobutton"));
        coarseAlignment_radiobutton->setGeometry(QRect(30, 20, 131, 20));
        coarseAlignment_radiobutton->setChecked(true);
        fineAlignment_radiobutton = new QRadioButton(attitudeControlTab);
        fineAlignment_radiobutton->setObjectName(QString::fromUtf8("fineAlignment_radiobutton"));
        fineAlignment_radiobutton->setGeometry(QRect(30, 50, 131, 20));
        line = new QFrame(attitudeControlTab);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(250, 20, 20, 381));
        line->setFrameShape(QFrame::VLine);
        line->setFrameShadow(QFrame::Sunken);
        simulationButton = new QPushButton(attitudeControlTab);
        simulationButton->setObjectName(QString::fromUtf8("simulationButton"));
        simulationButton->setGeometry(QRect(30, 350, 191, 21));
        simulationButton->setCheckable(false);
        simulationButton->setChecked(false);
        simulationButton->setAutoExclusive(false);
        simulationButton->setAutoDefault(false);
        simulationButton->setDefault(false);
        simulationButton->setFlat(false);
        tabWidget->addTab(attitudeControlTab, QString());
        sensorReadingsTab = new QWidget();
        sensorReadingsTab->setObjectName(QString::fromUtf8("sensorReadingsTab"));
        accelerometerBox = new QGroupBox(sensorReadingsTab);
        accelerometerBox->setObjectName(QString::fromUtf8("accelerometerBox"));
        accelerometerBox->setGeometry(QRect(20, 10, 341, 191));
        accelX_label = new QLabel(accelerometerBox);
        accelX_label->setObjectName(QString::fromUtf8("accelX_label"));
        accelX_label->setGeometry(QRect(0, 30, 41, 21));
        accelX_label->setAlignment(Qt::AlignCenter);
        accelY_label = new QLabel(accelerometerBox);
        accelY_label->setObjectName(QString::fromUtf8("accelY_label"));
        accelY_label->setGeometry(QRect(0, 80, 41, 21));
        accelY_label->setAlignment(Qt::AlignCenter);
        accelZ_label = new QLabel(accelerometerBox);
        accelZ_label->setObjectName(QString::fromUtf8("accelZ_label"));
        accelZ_label->setGeometry(QRect(0, 130, 41, 21));
        accelZ_label->setAlignment(Qt::AlignCenter);
        accelX_spinbox = new QDoubleSpinBox(accelerometerBox);
        accelX_spinbox->setObjectName(QString::fromUtf8("accelX_spinbox"));
        accelX_spinbox->setGeometry(QRect(40, 30, 101, 21));
        accelX_spinbox->setReadOnly(true);
        accelX_spinbox->setDecimals(4);
        accelX_spinbox->setMinimum(-2);
        accelX_spinbox->setMaximum(2);
        accelY_spinbox = new QDoubleSpinBox(accelerometerBox);
        accelY_spinbox->setObjectName(QString::fromUtf8("accelY_spinbox"));
        accelY_spinbox->setGeometry(QRect(40, 80, 101, 25));
        accelY_spinbox->setReadOnly(true);
        accelY_spinbox->setDecimals(4);
        accelY_spinbox->setMinimum(-2);
        accelY_spinbox->setMaximum(2);
        accelZ_spinbox = new QDoubleSpinBox(accelerometerBox);
        accelZ_spinbox->setObjectName(QString::fromUtf8("accelZ_spinbox"));
        accelZ_spinbox->setGeometry(QRect(40, 130, 101, 25));
        accelZ_spinbox->setReadOnly(true);
        accelZ_spinbox->setDecimals(4);
        accelZ_spinbox->setMinimum(-2);
        accelZ_spinbox->setMaximum(2);
        progressBarAccXPos = new QProgressBar(accelerometerBox);
        progressBarAccXPos->setObjectName(QString::fromUtf8("progressBarAccXPos"));
        progressBarAccXPos->setGeometry(QRect(240, 30, 81, 23));
        progressBarAccXPos->setMaximum(1050);
        progressBarAccXPos->setValue(0);
        progressBarAccXNeg = new QProgressBar(accelerometerBox);
        progressBarAccXNeg->setObjectName(QString::fromUtf8("progressBarAccXNeg"));
        progressBarAccXNeg->setGeometry(QRect(160, 30, 81, 21));
        progressBarAccXNeg->setMaximum(1050);
        progressBarAccXNeg->setValue(0);
        progressBarAccXNeg->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        progressBarAccXNeg->setInvertedAppearance(true);
        progressBarAccYNeg = new QProgressBar(accelerometerBox);
        progressBarAccYNeg->setObjectName(QString::fromUtf8("progressBarAccYNeg"));
        progressBarAccYNeg->setGeometry(QRect(160, 80, 81, 23));
        progressBarAccYNeg->setMaximum(1050);
        progressBarAccYNeg->setValue(0);
        progressBarAccYNeg->setInvertedAppearance(true);
        progressBarAccYPos = new QProgressBar(accelerometerBox);
        progressBarAccYPos->setObjectName(QString::fromUtf8("progressBarAccYPos"));
        progressBarAccYPos->setGeometry(QRect(240, 80, 81, 23));
        progressBarAccYPos->setMaximum(1050);
        progressBarAccYPos->setValue(0);
        progressBarAccZPos = new QProgressBar(accelerometerBox);
        progressBarAccZPos->setObjectName(QString::fromUtf8("progressBarAccZPos"));
        progressBarAccZPos->setGeometry(QRect(240, 130, 81, 23));
        progressBarAccZPos->setMaximum(1050);
        progressBarAccZPos->setValue(0);
        progressBarAccZNeg = new QProgressBar(accelerometerBox);
        progressBarAccZNeg->setObjectName(QString::fromUtf8("progressBarAccZNeg"));
        progressBarAccZNeg->setGeometry(QRect(160, 130, 81, 23));
        progressBarAccZNeg->setMaximum(1050);
        progressBarAccZNeg->setValue(0);
        progressBarAccZNeg->setInvertedAppearance(true);
        gyroscopeBox = new QGroupBox(sensorReadingsTab);
        gyroscopeBox->setObjectName(QString::fromUtf8("gyroscopeBox"));
        gyroscopeBox->setGeometry(QRect(20, 210, 341, 191));
        gyroX_label = new QLabel(gyroscopeBox);
        gyroX_label->setObjectName(QString::fromUtf8("gyroX_label"));
        gyroX_label->setGeometry(QRect(0, 30, 41, 21));
        gyroX_label->setAlignment(Qt::AlignCenter);
        gyroY_label = new QLabel(gyroscopeBox);
        gyroY_label->setObjectName(QString::fromUtf8("gyroY_label"));
        gyroY_label->setGeometry(QRect(0, 80, 41, 21));
        gyroY_label->setAlignment(Qt::AlignCenter);
        gyroZ_label = new QLabel(gyroscopeBox);
        gyroZ_label->setObjectName(QString::fromUtf8("gyroZ_label"));
        gyroZ_label->setGeometry(QRect(0, 130, 41, 21));
        gyroZ_label->setAlignment(Qt::AlignCenter);
        gyroX_spinbox = new QDoubleSpinBox(gyroscopeBox);
        gyroX_spinbox->setObjectName(QString::fromUtf8("gyroX_spinbox"));
        gyroX_spinbox->setGeometry(QRect(40, 30, 101, 25));
        gyroX_spinbox->setReadOnly(true);
        gyroX_spinbox->setDecimals(4);
        gyroX_spinbox->setMinimum(-500);
        gyroX_spinbox->setMaximum(500);
        gyroY_spinbox = new QDoubleSpinBox(gyroscopeBox);
        gyroY_spinbox->setObjectName(QString::fromUtf8("gyroY_spinbox"));
        gyroY_spinbox->setGeometry(QRect(40, 80, 101, 25));
        gyroY_spinbox->setReadOnly(true);
        gyroY_spinbox->setDecimals(4);
        gyroY_spinbox->setMinimum(-500);
        gyroY_spinbox->setMaximum(500);
        gyroZ_spinbox = new QDoubleSpinBox(gyroscopeBox);
        gyroZ_spinbox->setObjectName(QString::fromUtf8("gyroZ_spinbox"));
        gyroZ_spinbox->setGeometry(QRect(40, 130, 101, 25));
        gyroZ_spinbox->setReadOnly(true);
        gyroZ_spinbox->setDecimals(4);
        gyroZ_spinbox->setMinimum(-500);
        gyroZ_spinbox->setMaximum(500);
        progressBarGyroXNeg = new QProgressBar(gyroscopeBox);
        progressBarGyroXNeg->setObjectName(QString::fromUtf8("progressBarGyroXNeg"));
        progressBarGyroXNeg->setGeometry(QRect(160, 30, 81, 31));
        progressBarGyroXNeg->setMaximum(500);
        progressBarGyroXNeg->setValue(0);
        progressBarGyroXNeg->setAlignment(Qt::AlignCenter);
        progressBarGyroXNeg->setInvertedAppearance(true);
        progressBarGyroYNeg = new QProgressBar(gyroscopeBox);
        progressBarGyroYNeg->setObjectName(QString::fromUtf8("progressBarGyroYNeg"));
        progressBarGyroYNeg->setGeometry(QRect(160, 80, 81, 21));
        progressBarGyroYNeg->setMaximum(500);
        progressBarGyroYNeg->setValue(0);
        progressBarGyroYNeg->setInvertedAppearance(true);
        progressBarGyroZNeg = new QProgressBar(gyroscopeBox);
        progressBarGyroZNeg->setObjectName(QString::fromUtf8("progressBarGyroZNeg"));
        progressBarGyroZNeg->setGeometry(QRect(160, 130, 81, 21));
        progressBarGyroZNeg->setMaximum(500);
        progressBarGyroZNeg->setValue(0);
        progressBarGyroZNeg->setInvertedAppearance(true);
        progressBarGyroXPos = new QProgressBar(gyroscopeBox);
        progressBarGyroXPos->setObjectName(QString::fromUtf8("progressBarGyroXPos"));
        progressBarGyroXPos->setGeometry(QRect(240, 30, 81, 31));
        progressBarGyroXPos->setMaximum(500);
        progressBarGyroXPos->setValue(0);
        progressBarGyroXPos->setAlignment(Qt::AlignCenter);
        progressBarGyroYPos = new QProgressBar(gyroscopeBox);
        progressBarGyroYPos->setObjectName(QString::fromUtf8("progressBarGyroYPos"));
        progressBarGyroYPos->setGeometry(QRect(240, 80, 81, 21));
        progressBarGyroYPos->setMaximum(500);
        progressBarGyroYPos->setValue(0);
        progressBarGyroZPos = new QProgressBar(gyroscopeBox);
        progressBarGyroZPos->setObjectName(QString::fromUtf8("progressBarGyroZPos"));
        progressBarGyroZPos->setGeometry(QRect(240, 130, 81, 21));
        progressBarGyroZPos->setMaximum(500);
        progressBarGyroZPos->setValue(0);
        magnetoBox = new QGroupBox(sensorReadingsTab);
        magnetoBox->setObjectName(QString::fromUtf8("magnetoBox"));
        magnetoBox->setGeometry(QRect(390, 210, 341, 191));
        magX_label = new QLabel(magnetoBox);
        magX_label->setObjectName(QString::fromUtf8("magX_label"));
        magX_label->setGeometry(QRect(0, 30, 41, 21));
        magX_label->setAlignment(Qt::AlignCenter);
        magY_label = new QLabel(magnetoBox);
        magY_label->setObjectName(QString::fromUtf8("magY_label"));
        magY_label->setGeometry(QRect(0, 80, 41, 21));
        magY_label->setAlignment(Qt::AlignCenter);
        magZ_label = new QLabel(magnetoBox);
        magZ_label->setObjectName(QString::fromUtf8("magZ_label"));
        magZ_label->setGeometry(QRect(0, 130, 41, 21));
        magZ_label->setAlignment(Qt::AlignCenter);
        magX_spinbox = new QDoubleSpinBox(magnetoBox);
        magX_spinbox->setObjectName(QString::fromUtf8("magX_spinbox"));
        magX_spinbox->setGeometry(QRect(40, 30, 101, 25));
        magX_spinbox->setReadOnly(true);
        magX_spinbox->setDecimals(4);
        magX_spinbox->setMinimum(-1000);
        magX_spinbox->setMaximum(1000);
        magY_spinbox = new QDoubleSpinBox(magnetoBox);
        magY_spinbox->setObjectName(QString::fromUtf8("magY_spinbox"));
        magY_spinbox->setGeometry(QRect(40, 80, 101, 25));
        magY_spinbox->setReadOnly(true);
        magY_spinbox->setDecimals(4);
        magY_spinbox->setMinimum(-1000);
        magY_spinbox->setMaximum(1000);
        magZ_spinbox = new QDoubleSpinBox(magnetoBox);
        magZ_spinbox->setObjectName(QString::fromUtf8("magZ_spinbox"));
        magZ_spinbox->setGeometry(QRect(40, 130, 101, 25));
        magZ_spinbox->setReadOnly(true);
        magZ_spinbox->setDecimals(4);
        magZ_spinbox->setMinimum(-1000);
        magZ_spinbox->setMaximum(1000);
        progressBarMagXNeg = new QProgressBar(magnetoBox);
        progressBarMagXNeg->setObjectName(QString::fromUtf8("progressBarMagXNeg"));
        progressBarMagXNeg->setGeometry(QRect(160, 30, 81, 23));
        progressBarMagXNeg->setMaximum(1000);
        progressBarMagXNeg->setValue(0);
        progressBarMagXNeg->setInvertedAppearance(true);
        progressBarMagYNeg = new QProgressBar(magnetoBox);
        progressBarMagYNeg->setObjectName(QString::fromUtf8("progressBarMagYNeg"));
        progressBarMagYNeg->setGeometry(QRect(160, 80, 81, 23));
        progressBarMagYNeg->setMaximum(1000);
        progressBarMagYNeg->setValue(0);
        progressBarMagYNeg->setInvertedAppearance(true);
        progressBarMagZNeg = new QProgressBar(magnetoBox);
        progressBarMagZNeg->setObjectName(QString::fromUtf8("progressBarMagZNeg"));
        progressBarMagZNeg->setGeometry(QRect(160, 130, 81, 23));
        progressBarMagZNeg->setMaximum(1000);
        progressBarMagZNeg->setValue(0);
        progressBarMagZNeg->setInvertedAppearance(true);
        progressBarMagXPos = new QProgressBar(magnetoBox);
        progressBarMagXPos->setObjectName(QString::fromUtf8("progressBarMagXPos"));
        progressBarMagXPos->setGeometry(QRect(240, 30, 81, 23));
        progressBarMagXPos->setMaximum(1000);
        progressBarMagXPos->setValue(0);
        progressBarMagYPos = new QProgressBar(magnetoBox);
        progressBarMagYPos->setObjectName(QString::fromUtf8("progressBarMagYPos"));
        progressBarMagYPos->setGeometry(QRect(240, 80, 81, 23));
        progressBarMagYPos->setMaximum(1000);
        progressBarMagYPos->setValue(0);
        progressBarMagZPos = new QProgressBar(magnetoBox);
        progressBarMagZPos->setObjectName(QString::fromUtf8("progressBarMagZPos"));
        progressBarMagZPos->setGeometry(QRect(240, 130, 81, 23));
        progressBarMagZPos->setMaximum(1000);
        progressBarMagZPos->setValue(0);
        groupBox = new QGroupBox(sensorReadingsTab);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(580, 10, 151, 191));
        progressBar1Neg = new QProgressBar(groupBox);
        progressBar1Neg->setObjectName(QString::fromUtf8("progressBar1Neg"));
        progressBar1Neg->setGeometry(QRect(30, 100, 21, 61));
        progressBar1Neg->setContextMenuPolicy(Qt::DefaultContextMenu);
        progressBar1Neg->setLayoutDirection(Qt::LeftToRight);
        progressBar1Neg->setAutoFillBackground(false);
        progressBar1Neg->setMaximum(3000);
        progressBar1Neg->setValue(0);
        progressBar1Neg->setOrientation(Qt::Vertical);
        progressBar1Neg->setInvertedAppearance(true);
        progressBar2Neg = new QProgressBar(groupBox);
        progressBar2Neg->setObjectName(QString::fromUtf8("progressBar2Neg"));
        progressBar2Neg->setGeometry(QRect(70, 100, 21, 61));
        progressBar2Neg->setMaximum(3000);
        progressBar2Neg->setValue(0);
        progressBar2Neg->setOrientation(Qt::Vertical);
        progressBar2Neg->setInvertedAppearance(true);
        progressBar3Neg = new QProgressBar(groupBox);
        progressBar3Neg->setObjectName(QString::fromUtf8("progressBar3Neg"));
        progressBar3Neg->setGeometry(QRect(110, 100, 21, 61));
        progressBar3Neg->setMaximum(3000);
        progressBar3Neg->setValue(0);
        progressBar3Neg->setOrientation(Qt::Vertical);
        progressBar3Neg->setInvertedAppearance(true);
        label = new QLabel(groupBox);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(20, 160, 41, 21));
        label->setAlignment(Qt::AlignCenter);
        label_2 = new QLabel(groupBox);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(60, 160, 41, 21));
        label_2->setAlignment(Qt::AlignCenter);
        label_3 = new QLabel(groupBox);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(100, 160, 41, 21));
        label_3->setAlignment(Qt::AlignCenter);
        progressBar1Pos = new QProgressBar(groupBox);
        progressBar1Pos->setObjectName(QString::fromUtf8("progressBar1Pos"));
        progressBar1Pos->setGeometry(QRect(30, 40, 21, 61));
        progressBar1Pos->setContextMenuPolicy(Qt::DefaultContextMenu);
        progressBar1Pos->setLayoutDirection(Qt::LeftToRight);
        progressBar1Pos->setAutoFillBackground(false);
        progressBar1Pos->setMaximum(3000);
        progressBar1Pos->setValue(0);
        progressBar1Pos->setOrientation(Qt::Vertical);
        progressBar1Pos->setInvertedAppearance(false);
        progressBar2Pos = new QProgressBar(groupBox);
        progressBar2Pos->setObjectName(QString::fromUtf8("progressBar2Pos"));
        progressBar2Pos->setGeometry(QRect(70, 40, 21, 61));
        progressBar2Pos->setMaximum(3000);
        progressBar2Pos->setValue(0);
        progressBar2Pos->setOrientation(Qt::Vertical);
        progressBar3Pos = new QProgressBar(groupBox);
        progressBar3Pos->setObjectName(QString::fromUtf8("progressBar3Pos"));
        progressBar3Pos->setGeometry(QRect(110, 40, 21, 61));
        progressBar3Pos->setMaximum(3000);
        progressBar3Pos->setValue(0);
        progressBar3Pos->setOrientation(Qt::Vertical);
        IR_graphics = new QGraphicsView(sensorReadingsTab);
        IR_graphics->setObjectName(QString::fromUtf8("IR_graphics"));
        IR_graphics->setGeometry(QRect(410, 50, 131, 131));
        IR_graphics->setFrameShape(QFrame::StyledPanel);
        IR_graphics->setSceneRect(QRectF(0, 0, 123, 123));
        IR_label = new QLabel(sensorReadingsTab);
        IR_label->setObjectName(QString::fromUtf8("IR_label"));
        IR_label->setGeometry(QRect(410, 30, 131, 16));
        QFont font;
        font.setPointSize(12);
        IR_label->setFont(font);
        IR_label->setAlignment(Qt::AlignCenter);
        tabWidget->addTab(sensorReadingsTab, QString());
        state_label = new QLabel(centralWidget);
        state_label->setObjectName(QString::fromUtf8("state_label"));
        state_label->setGeometry(QRect(30, 10, 51, 21));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Lucida Grande"));
        state_label->setFont(font1);
        state_label->setTextFormat(Qt::RichText);
        state_label2 = new QLabel(centralWidget);
        state_label2->setObjectName(QString::fromUtf8("state_label2"));
        state_label2->setGeometry(QRect(80, 10, 151, 21));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 800, 22));
        menuConnection = new QMenu(menuBar);
        menuConnection->setObjectName(QString::fromUtf8("menuConnection"));
        menuAbout = new QMenu(menuBar);
        menuAbout->setObjectName(QString::fromUtf8("menuAbout"));
        menuWindow = new QMenu(menuBar);
        menuWindow->setObjectName(QString::fromUtf8("menuWindow"));
        MainWindow->setMenuBar(menuBar);

        menuBar->addAction(menuConnection->menuAction());
        menuBar->addAction(menuWindow->menuAction());
        menuBar->addAction(menuAbout->menuAction());
        menuConnection->addAction(connectAction);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0, QApplication::UnicodeUTF8));
        connectAction->setText(QApplication::translate("MainWindow", "Connect", 0, QApplication::UnicodeUTF8));
        Connect2->setText(QString());
        AccLabel_2->setText(QApplication::translate("MainWindow", "Connection string", 0, QApplication::UnicodeUTF8));
        currentQuaternionBox->setTitle(QApplication::translate("MainWindow", "Current Quaternions", 0, QApplication::UnicodeUTF8));
        cur_q0_label->setText(QApplication::translate("MainWindow", "q0", 0, QApplication::UnicodeUTF8));
        cur_q1_label->setText(QApplication::translate("MainWindow", "q1", 0, QApplication::UnicodeUTF8));
        cur_q2_label->setText(QApplication::translate("MainWindow", "q2", 0, QApplication::UnicodeUTF8));
        cur_q3_label->setText(QApplication::translate("MainWindow", "q3", 0, QApplication::UnicodeUTF8));
        setupQuaternionBox->setTitle(QApplication::translate("MainWindow", "Quaternion Setup", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_TOOLTIP
        roll_dial->setToolTip(QString());
#endif // QT_NO_TOOLTIP
#ifndef QT_NO_ACCESSIBILITY
        pitch_dial->setAccessibleName(QString());
#endif // QT_NO_ACCESSIBILITY
#ifndef QT_NO_ACCESSIBILITY
        pitch_dial->setAccessibleDescription(QString());
#endif // QT_NO_ACCESSIBILITY
        roll_label->setText(QApplication::translate("MainWindow", "Roll", 0, QApplication::UnicodeUTF8));
        yaw_label->setText(QApplication::translate("MainWindow", "Yaw", 0, QApplication::UnicodeUTF8));
        pitch_label->setText(QApplication::translate("MainWindow", "Pitch", 0, QApplication::UnicodeUTF8));
        q0_label->setText(QApplication::translate("MainWindow", "q0", 0, QApplication::UnicodeUTF8));
        q1_label->setText(QApplication::translate("MainWindow", "q1", 0, QApplication::UnicodeUTF8));
        q2_label->setText(QApplication::translate("MainWindow", "q2", 0, QApplication::UnicodeUTF8));
        q3_label->setText(QApplication::translate("MainWindow", "q3", 0, QApplication::UnicodeUTF8));
        coarseAlignment_radiobutton->setText(QApplication::translate("MainWindow", "Coarse alignment", 0, QApplication::UnicodeUTF8));
        fineAlignment_radiobutton->setText(QApplication::translate("MainWindow", "Fine alignment", 0, QApplication::UnicodeUTF8));
        simulationButton->setText(QApplication::translate("MainWindow", "Start Simulation", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(attitudeControlTab), QApplication::translate("MainWindow", "Attitude Control", 0, QApplication::UnicodeUTF8));
        accelerometerBox->setTitle(QApplication::translate("MainWindow", "Accelerometers", 0, QApplication::UnicodeUTF8));
        accelX_label->setText(QApplication::translate("MainWindow", "x", 0, QApplication::UnicodeUTF8));
        accelY_label->setText(QApplication::translate("MainWindow", "y", 0, QApplication::UnicodeUTF8));
        accelZ_label->setText(QApplication::translate("MainWindow", "z", 0, QApplication::UnicodeUTF8));
        gyroscopeBox->setTitle(QApplication::translate("MainWindow", "Gyroscopes", 0, QApplication::UnicodeUTF8));
        gyroX_label->setText(QApplication::translate("MainWindow", "x", 0, QApplication::UnicodeUTF8));
        gyroY_label->setText(QApplication::translate("MainWindow", "y", 0, QApplication::UnicodeUTF8));
        gyroZ_label->setText(QApplication::translate("MainWindow", "z", 0, QApplication::UnicodeUTF8));
        magnetoBox->setTitle(QApplication::translate("MainWindow", "Magnetometers", 0, QApplication::UnicodeUTF8));
        magX_label->setText(QApplication::translate("MainWindow", "x", 0, QApplication::UnicodeUTF8));
        magY_label->setText(QApplication::translate("MainWindow", "y", 0, QApplication::UnicodeUTF8));
        magZ_label->setText(QApplication::translate("MainWindow", "z", 0, QApplication::UnicodeUTF8));
        groupBox->setTitle(QApplication::translate("MainWindow", "Wheel speeds", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_TOOLTIP
        progressBar1Neg->setToolTip(QString());
#endif // QT_NO_TOOLTIP
        progressBar1Neg->setFormat(QApplication::translate("MainWindow", "%p%", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("MainWindow", "w1", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("MainWindow", "w2", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("MainWindow", "w3", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_TOOLTIP
        progressBar1Pos->setToolTip(QString());
#endif // QT_NO_TOOLTIP
        progressBar1Pos->setFormat(QApplication::translate("MainWindow", "%p%", 0, QApplication::UnicodeUTF8));
        IR_label->setText(QApplication::translate("MainWindow", "IR Camera", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(sensorReadingsTab), QApplication::translate("MainWindow", "Sensor Readings", 0, QApplication::UnicodeUTF8));
        state_label->setText(QApplication::translate("MainWindow", "STATE: ", 0, QApplication::UnicodeUTF8));
        state_label2->setText(QApplication::translate("MainWindow", "...", 0, QApplication::UnicodeUTF8));
        menuConnection->setTitle(QApplication::translate("MainWindow", "Connection", 0, QApplication::UnicodeUTF8));
        menuAbout->setTitle(QApplication::translate("MainWindow", "About", 0, QApplication::UnicodeUTF8));
        menuWindow->setTitle(QApplication::translate("MainWindow", "Window", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
